### ISSUE TITLE
Error trying to use PN532 from JavaScript

### ISSUE THREAD

**Issue by deadprogram** [intel-iot-devkit/upm#238]
When attempting to run the `pn532.js` example, I am receiving the following error:

```
Error: Cannot find module 'jsupm_pn532'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/root/blink/nfc.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I am running firmware 159 and the latest released mraa/upm

**Comment by w4ilun** [comment]
try opkg install upm after updating the repo:

echo "src mraa-upm http://iotdk.intel.com/repos/1.1/intelgalactic" > /etc/opkg/mraa-upm.conf
opkg update
opkg install upm
