### ISSUE TITLE
Illegal arguments for construction of _exports_SAINSMARTKS in JS module installed from npm with UPM 1.0.0-src

### ISSUE THREAD

**Issue by deadprogram** [intel-iot-devkit/upm#498]
I am receiving an error when attempting to use the SAINSMARTKS LCD display, from JS for UPM version 1.0.0-src when installed via the jsupm_i2clcd module using npm.

I receive the following error:

```
ERROR: var lcd = new sainsmartObj.SAINSMARTKS();
ERROR:           ^

ERROR: Error: Illegal arguments for construction of _exports_SAINSMARTKS
    at Error (native)
    at Object.<anonymous> (/home/root/.node_app_slot/index.js:28:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by deadprogram** [comment]
This was addressed in upm 1.0.2 thanks everyone. Now closing this issue.
